export const reduxActionTypes = {
    SET_USER: 'SET_USER',
    REMOVE_USER:'REMOVE_USER',
    SET_POSTS:'SET_POSTS',
    GET_MORE_POSTS:'GET_MORE_POSTS',
    UPDATE_POST:'UPDATE_POST',
    CREATE_POST:'CREATE_POST',
    INCREMENT_COUNT:'INCREMENT_COUNT',
    DECREMENT_COUNT:'DECREMENT_COUNT',
    HAS_MORE_POSTS:'HAS_MORE_POSTS',
}